# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62784c60ba7ea6c98b0f91efcd195598ce1ac7526ab45aa518852035760075b4d91608e65d85625288478932bbdc774fe3bd0c9d4f881d390879c9613ee9a375

test:
  secret_key_base: 8602b71fcd2a53d4c46af9d1efec4ebd5f21c80ef7cbc0ca520a9dcea46488144de8ac0553a78933578ea8f272fee7850961a80b3e5ee2425a50d17a272c850f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
